### ISSUE TITLE
tangent_identity_field no longer seen as a tensor-field

### ISSUE THREAD

**Issue by bpillet** [sagemanifolds/SageManifolds#1]
Since I moved to sagemanifold v0.7 with sage v6.5 there is no longer coertion from the tangent_identy_field to a (1,1)-tensor field

There is a tangent_identity_field for any manifold 'M'

```
Id = M.tangent_identity_field(); Id.parent()

General linear group of the module X(M) of vector
fields on the 4-dimensional manifold 'M'
```

Meanwhile

```
Id2 = M.tensor_field(1,1); Id2.parent()

module T^(1,1)(M) of type-(1,1) tensors fields on the
4-dimensional manifold 'M'
```

Using `Id2.parent().coerc(Id)` one gets the following error

```
TypeError: no canonical coercion from General linear group of the module
X(M) of vector fields on the 4-dimensional manifold
'M' to module T^(1,1)(M) of type-(1,1)
tensors fields on the 4-dimensional manifold 'M'
```

There ought to be other ways to create the identity (1,1)-tensor field, but this one seemed the most natural.

I hope this is the right place for such question.
Sincerly,
Basile Pillet

**Comment by sagemanifolds** [comment]
Hi Basile, 
Good catch!
Actually the coercion GL(X(M)) --> T^(1,1)(M) is implemented when M is a parallelizable manifold, i.e. when X(M) and T^(1,1)(M) are both free modules:

```
sage: M = Manifold(4, 'M')
sage: X.<t,x,y,z> = M.chart()  # makes M parallelizable (as a chart domain)
sage: M.is_manifestly_parallelizable()
True
sage: Id = M.tangent_identity_field(); Id.parent()
General linear group of the free module X(M) of vector fields on the 4-dimensional manifold 'M'
sage: Id2 = M.tensor_field(1,1); Id2.parent()
free module T^(1,1)(M) of type-(1,1) tensors fields on the 4-dimensional manifold 'M'
sage: Id2.parent().coerce(Id)
tensor field 'Id' of type (1,1) on the 4-dimensional manifold 'M'
```

In the generic case, it is not implemented yet, but it should be!
To be added soon in the development version!
Eric.

**Comment by sagemanifolds** [comment]
The missing coercion has just been implemented in the latest development version (commit 144d81bf0a on the master branch of https://github.com/sagemanifolds/sage.git).
So if you perform
`git pull sm-github master`
you should be fine. 

Eric.
