### ISSUE TITLE
SageManifolds on SageMath Cloud

### ISSUE THREAD

**Issue by tobiasdiez** [sagemanifolds/SageManifolds#2]
I have problems running the more advanced features of SageManifolds (like tangent spaces, Riemannian metrics, etc) on SageMath Cloud.
For example, I get the following error

> raise dummy_attribute_error
> AttributeError: 'DifferentiableManifold_with_category' object has no attribute 'metric'

I think the reason is that sage 7.3 includes only the rudimentary part of the manifolds package. How can I install manifolds 0.9.1 on the cloud (I tried the usual approach but internet access is blocked on the free account and in addition, I don't have write permission in the sage folder).

**Comment by egourgoulhon** [comment]
You are right, SageManifolds was installed in SageMathCloud when the latter was running Sage 6.10, but not in the Sage 7.3 version. Hopefully, it has been restored with the upgrade of SageMathCLoud to Sage 7.4. For instance, if you open a Jupyter worksheet, click on the "kernel" button, then to "Change kernel" and select "SageMath 7.4": then you will have access to the full SageManifolds (version 0.9.1).

**Comment by tobiasdiez** [comment]
Thanks!
